import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const base = process.env.QA_URL || 'http://127.0.0.1:5189/';
const out = process.env.QA_OUT || 'artifacts/production';
await mkdir(out, { recursive: true });
const isLocal = ['127.0.0.1', 'localhost'].includes(new URL(base).hostname);
const health = isLocal ? await (await fetch(new URL('/__sakura_health', base))).json() : null;
if (health) assert.equal(health.app, 'sakura-walk');
const browser = await chromium.launch({ channel: 'chromium' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [], externalRequests = [];
const assets = [];
page.on('response', response => {
  if (response.status() >= 400) errors.push(`HTTP ${response.status()}: ${response.url()}`);
  if (response.url().endsWith('.vrm')) assets.push({ url: response.url(), status: response.status() });
});
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
page.on('request', request => {
  if (/^https?:/.test(request.url()) && new URL(request.url()).origin !== new URL(base).origin) externalRequests.push(request.url());
});
page.on('requestfailed', request => errors.push(`${request.url()}: ${request.failure()?.errorText}`));
await page.goto(base);
await page.waitForFunction(() => !document.querySelector('#begin').disabled, null, { timeout: 120000 });
await page.evaluate(() => document.fonts.ready);
await page.screenshot({ path: `${out}/welcome.png` });
const debugAbsent = await page.evaluate(() => !window.__SAKURA__ && !window.__THREE_GAME_TEST_HOOKS__ && !window.__THREE_GAME_DIAGNOSTICS__);
assert(debugAbsent, 'QA hooks must be absent from a normal launch');
await page.locator('#begin').click();
await page.keyboard.down('KeyW');
await page.waitForTimeout(1400);
await page.keyboard.up('KeyW');
await page.keyboard.press('Escape');
assert(await page.locator('#settings').isVisible());
await page.setViewportSize({ width: 1280, height: 720 });
const pauseFit = await page.locator('#settings').evaluate(e => {
  const dialog = e.getBoundingClientRect(), controls = e.querySelector('.settings-controls').getBoundingClientRect();
  return dialog.top >= 0 && dialog.bottom <= innerHeight && controls.bottom <= dialog.bottom - 10 && e.scrollHeight <= e.clientHeight + 2;
});
assert(pauseFit, 'All pause controls must fit the 720px viewport');
await page.screenshot({ path: `${out}/pause-720.png` });
await page.locator('#resume').click();
assert(!(await page.locator('#settings').isVisible()));
await page.keyboard.press('KeyV');
assert(await page.locator('body').evaluate(e=>e.classList.contains('first-person')));
await page.locator('#look').click();
assert.equal(await page.locator('#look').getAttribute('aria-pressed'),'true');
await page.keyboard.down('KeyW');
await page.waitForTimeout(1400);
await page.keyboard.up('KeyW');
await page.waitForTimeout(500);
await page.screenshot({path:`${out}/first-person.png`});
await page.keyboard.press('KeyV');
assert(!(await page.locator('body').evaluate(e=>e.classList.contains('first-person'))));
assert.deepEqual(errors, []);
assert.deepEqual(externalRequests, []);
assert.equal(assets.length, 2, 'Both bundled VRM models must load');
assert(assets.every(asset => asset.status === 200));
const result = { base, health, debugAbsent, startPauseResume: true, perspectiveAndGaze:true, pauseFit, assets, errors, externalRequests, checkedAt: new Date().toISOString() };
await writeFile(`${out}/smoke.json`, JSON.stringify(result, null, 2));
console.log(JSON.stringify(result));
await browser.close();
