import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const output=process.env.QA_OUT||'artifacts/verification';await mkdir(output,{recursive:true});
const appUrl=(process.env.QA_URL||'http://127.0.0.1:5188/').replace(/\/$/,'')+'/?qa=1';
const browser=await chromium.launch({channel:'chromium'});const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1,recordVideo:{dir:`${output}/motion`,size:{width:1440,height:900}},acceptDownloads:true});
const page=await context.newPage(),errors=[],failedRequests=[],checks=[],samples=[];const snap=()=>page.evaluate(()=>window.__SAKURA__.state());
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('requestfailed',r=>failedRequests.push({url:r.url(),error:r.failure()?.errorText}));
async function check(name,fn){try{await fn();checks.push({name,pass:true});console.log(`PASS ${name}`);}catch(e){checks.push({name,pass:false,error:e.message});console.log(`FAIL ${name}: ${e.message}`);}}
async function key(code,duration){await page.keyboard.down(code);await page.waitForTimeout(duration);await page.keyboard.up(code);}
await page.goto(appUrl);await page.waitForFunction(()=>!!window.__SAKURA__,{timeout:60000});await page.locator('#begin').click();
await check('Start and gesture audio unlock',async()=>{const s=await snap();assert(s.started);assert.equal(s.audio.state,'running');});
await check('Both supplied VRM1 avatars replace the sample characters',async()=>{const s=await snap();assert.equal(s.companionModel.asset,'models/bbs-companion.vrm');assert.equal(s.playerModel.asset,'models/sssi-walker.vrm');assert.equal(s.companionModel.format,'VRM1-skinned');assert.equal(s.playerModel.format,'VRM1-skinned');});
let previous=await snap();await key('KeyW',2600);let walking=await snap();samples.push({event:'forward',state:walking});
await check('Forward walking responds to real input',()=>assert(walking.player.z-previous.player.z>2));
await page.screenshot({path:`output-placeholder`.replace('output-placeholder',`${output}/walking.png`)});
await page.waitForTimeout(1400);let idle=await snap();samples.push({event:'stopped',state:idle});
await check('Companion settles beside stopped player',()=>{assert(idle.companion.speed<.16);assert(idle.player.speed<.015);assert(idle.companion.separation>.62&&idle.companion.separation<1.8);});
previous=idle;await key('KeyD',1300);let side=await snap();samples.push({event:'screen-right',state:side});
await check('Camera-relative screen-right direction',()=>assert(side.player.x<previous.player.x-.6));
await key('KeyS',2600);await page.waitForTimeout(900);let turn=await snap();samples.push({event:'turn-around',state:turn});
await check('Reverse movement and natural reformation',()=>{assert(turn.player.z<walking.player.z-1.6);assert(turn.companion.separation>.6&&turn.companion.separation<2.3);});
await page.screenshot({path:`${output}/turn.png`});
await page.keyboard.press('KeyE');await page.waitForTimeout(450);let greet=await snap();
await check('Greeting triggers wave and visible line',async()=>{assert(greet.companion.greeting>0);assert(await page.locator('#caption').evaluate(e=>e.classList.contains('visible')));});
await page.waitForTimeout(1700);await page.screenshot({path:`${output}/greeting.png`});
previous=await snap();await page.mouse.move(850,420);await page.mouse.down();await page.mouse.move(1130,455,{steps:20});await page.mouse.up();await page.waitForTimeout(700);let orbit=await snap();
await check('Mouse orbit updates camera',()=>assert(Math.abs(orbit.camera.yaw-previous.camera.yaw)>.7));
await page.mouse.wheel(0,-3000);await page.waitForTimeout(650);let safe=await snap();
await check('Safe camera floor and minimum zoom',()=>{assert(safe.camera.y>=1.79);assert(safe.camera.distance>=3.09);});
await page.keyboard.press('KeyP');await page.waitForTimeout(250);previous=await snap();await page.waitForTimeout(400);let frozen=await snap();
await check('Photo mode freezes locomotion',()=>{assert(frozen.photo);assert.equal(frozen.elapsed,previous.elapsed);});
const downloadPromise=page.waitForEvent('download');await page.locator('#save-photo').click();const download=await downloadPromise;await download.saveAs(`${output}/saved-photograph.png`);await page.keyboard.press('KeyP');
await check('Photo download produces PNG',()=>assert.equal(download.suggestedFilename(),'sakura-walk-moment.png'));
await page.keyboard.press('Escape');await page.waitForTimeout(300);previous=await snap();await page.waitForTimeout(300);let stopped=await snap();
await check('Pause freezes scene and audio',()=>{assert(stopped.paused);assert.equal(stopped.elapsed,previous.elapsed);assert.equal(stopped.audio.state,'suspended');});
await page.locator('#volume').fill('35');await page.locator('#music').uncheck();await page.locator('#quality').selectOption('balanced');await page.screenshot({path:`${output}/settings.png`});await page.locator('#resume').click();
await check('Settings are connected to runtime',async()=>{await page.waitForFunction(()=>window.__SAKURA__.state().audio.state==='running');const s=await snap();assert.equal(s.quality,'balanced');assert.equal(s.audio.volume,.35);assert(!s.audio.music);assert.equal(s.audio.state,'running');});
await page.keyboard.press('KeyM');await check('Mute control',async()=>assert((await snap()).audio.muted));await page.keyboard.press('KeyM');
await page.keyboard.press('Escape');await page.locator('#reset').click();previous=await snap();
await check('Return to entrance resets formation',()=>{assert(Math.abs(previous.player.z)<.01);assert(previous.companion.separation<1.6);});
await page.keyboard.press('Space');await page.waitForTimeout(1500);let stroll=await snap();await page.keyboard.press('Space');
await check('Auto-stroll moves and toggles off',async()=>{assert(stroll.autoWalk);assert(stroll.player.z>1);assert(!(await snap()).autoWalk);});
await key('KeyD',4200);await page.waitForTimeout(1500);let edge=await snap();samples.push({event:'path-edge',state:edge});
await check('Path boundary and companion side switch',()=>{assert(edge.player.x>=-3.001);assert(edge.companion.x>=-3.001);assert(edge.companion.separation>.62&&edge.companion.separation<1.8);assert(edge.companion.speed<.16);});
await page.keyboard.press('Escape');await page.locator('#quality').selectOption('high');await page.locator('#resume').click();
const gpu=await page.evaluate(()=>{const gl=document.querySelector('canvas').getContext('webgl2');const ext=gl.getExtension('WEBGL_debug_renderer_info');return {renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER)};});
await key('KeyW',1800);samples.push({event:'final-active',state:await snap()});await page.waitForTimeout(700);
await page.keyboard.press('Escape');await page.locator('#reset').click();await page.keyboard.press('KeyV');await page.waitForTimeout(500);
await check('First person switches to adult eye height and hides self',async()=>{const s=await snap();assert.equal(s.cameraMode,'first');assert(!s.playerVisible);assert(s.camera.y>1.55&&s.camera.y<1.85);assert(Math.hypot(s.camera.x-s.player.x,s.camera.z-s.player.z)<.05);});
await page.keyboard.press('KeyQ');await page.keyboard.down('KeyW');await page.waitForTimeout(3500);let together=await snap();samples.push({event:'first-person-together',state:together});
await check('First person looks at companion while walking the original direction',()=>{assert(together.lookTogether);assert(together.player.z>3);assert(Math.abs(together.player.x+.72)<.08);assert(Math.abs(together.player.speed-together.companion.speed)<.13);assert(together.companion.separation>1&&together.companion.separation<1.5);assert(Math.abs(together.companionLook)>.7);});
await page.screenshot({path:`${output}/first-person-walking.png`});await page.keyboard.up('KeyW');await page.waitForTimeout(1200);
await check('First-person companion stops in formation',async()=>{const s=await snap();assert(s.player.speed<.02);assert(s.companion.speed<.12);});
await page.keyboard.press('KeyE');await page.waitForTimeout(500);await page.screenshot({path:`${output}/first-person-greeting.png`});
await page.keyboard.press('KeyP');await page.waitForTimeout(250);await page.keyboard.press('KeyP');await page.waitForTimeout(250);
await check('Photo mode restores first-person perspective and gaze',async()=>{const s=await snap();assert.equal(s.cameraMode,'first');assert(s.lookTogether);assert(!s.playerVisible);});
await page.mouse.move(700,450);await page.mouse.down();await page.mouse.move(880,465,{steps:12});await page.mouse.up();await page.waitForTimeout(500);
await check('First-person free look releases companion focus',async()=>{const s=await snap();assert(!s.lookTogether);assert.equal(s.cameraMode,'first');assert(s.camera.firstPitch>=-.5);});
await page.keyboard.press('KeyV');await check('Third person restores visible male avatar',async()=>{const s=await snap();assert.equal(s.cameraMode,'third');assert(s.playerVisible);});
const video=page.video();await context.close();await video.saveAs(`${output}/locomotion.webm`);

const mobileContext=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const mobile=await mobileContext.newPage();mobile.on('pageerror',e=>errors.push(`mobile: ${e.message}`));
await mobile.goto(appUrl);await mobile.waitForFunction(()=>!!window.__SAKURA__);await mobile.locator('#begin').click();await mobile.waitForTimeout(500);
const mobileState=()=>mobile.evaluate(()=>window.__SAKURA__.state());const beforeTouch=await mobileState();const joy=await mobile.locator('#joystick').boundingBox();
await mobile.mouse.move(joy.x+joy.width/2,joy.y+joy.height/2);await mobile.mouse.down();await mobile.mouse.move(joy.x+joy.width/2,joy.y+15,{steps:6});await mobile.waitForTimeout(1500);await mobile.mouse.up();await mobile.waitForTimeout(600);const afterTouch=await mobileState();
await check('Touch joystick emits movement and releases',()=>{assert(afterTouch.player.z>beforeTouch.player.z+.7);assert(afterTouch.player.speed<.03);});
await mobile.screenshot({path:`${output}/mobile-active.png`});
await mobile.locator('#touch-stroll').click();await mobile.waitForTimeout(500);await mobile.locator('#touch-stroll').click();
await mobile.mouse.move(310,310);await mobile.mouse.down();await mobile.mouse.move(180,335,{steps:10});await mobile.mouse.up();await mobile.waitForTimeout(400);
await check('Touch-screen orbit and readable viewport',async()=>{assert(Math.abs((await mobileState()).camera.yaw-afterTouch.camera.yaw)>.2);const overflow=await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow);});
await mobile.setViewportSize({width:844,height:390});await mobile.waitForTimeout(500);await mobile.screenshot({path:`${output}/mobile-landscape.png`});
await check('Landscape resize retains nonzero canvas',async()=>{const bounds=await mobile.locator('#world').boundingBox();assert.equal(bounds.width,844);assert.equal(bounds.height,390);});
await mobile.locator('#view').click();await mobile.locator('#touch-look').click();await mobile.waitForTimeout(800);await mobile.screenshot({path:`${output}/mobile-first-person.png`});
await check('Touch perspective and look-at controls work',async()=>{const s=await mobileState();assert.equal(s.cameraMode,'first');assert(s.lookTogether);assert(!await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth));});
await mobileContext.close();await browser.close();
checks.push({name:'Browser console and requests',pass:errors.length===0&&failedRequests.length===0,errors,failedRequests});
await writeFile(`${output}/behavior.json`,JSON.stringify({checks,samples,gpu,errors,failedRequests,mobile:{beforeTouch,afterTouch}},null,2));
console.log(JSON.stringify({passed:checks.filter(c=>c.pass).length,total:checks.length,gpu,errors,failedRequests}));if(checks.some(c=>!c.pass))process.exitCode=1;
